format = "$fill $all| [ $directory](inverted)$line_break$character"

[character]
success_symbol = "[ğŸ®™](bold green inverted)"
error_symbol = "[ğŸ®™](bold red inverted)"
vicmd_symbol = "[ğŸ®–](bold blue inverted)"

[git_status]
disabled = true

[package]
display_private = true

[directory]
style = "inverted"

[git_branch]
format = "[$symbol$branch]($style) "

[cmd_duration]
format = "â±ï¸[$duration]($style) "
